version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install --prefix cdk
  build:
    commands:
      - echo Build started on `date`
      - npm run build --prefix cdk || echo No build script defined
artifacts:
  files:
    - '**/*'
